import path from 'node:path';
import { mkdir, readFile, readdir, rm, writeFile, stat } from 'node:fs/promises';
import type { VideoProject } from '@guidedreel/core';
import { parseProjectDocument } from '@guidedreel/core';
import { createLogger } from '@guidedreel/core';
import type { StoredAssetMetaDTO } from '../shared/ipc';

const log = createLogger('desktop:storage', { level: 'info' });

/** Projects as individual project.json files under userData/projects. */
export class FileProjectRepository {
  constructor(private readonly dir: string) {}

  private file(id: string) {
    return path.join(this.dir, `${encodeURIComponent(id)}.json`);
  }

  async list() {
    await mkdir(this.dir, { recursive: true });
    const names = (await readdir(this.dir)).filter((n) => n.endsWith('.json'));
    const out = [];
    for (const n of names) {
      try {
        const parsed = parseProjectDocument(
          JSON.parse(await readFile(path.join(this.dir, n), 'utf8')),
        );
        if (parsed.success) {
          const p = parsed.data;
          out.push({
            id: p.id,
            name: p.name,
            templateId: p.templateId,
            format: p.format,
            sceneCount: p.scenes.length,
            createdAt: p.metadata.createdAt,
            updatedAt: p.metadata.updatedAt,
          });
        } else
          log.warn('skipping invalid project file', { file: n, issue: parsed.issues[0]?.message });
      } catch (err) {
        log.warn('could not read project file', { file: n, error: String(err) });
      }
    }
    return out.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  }

  async get(id: string): Promise<VideoProject | null> {
    try {
      const parsed = parseProjectDocument(JSON.parse(await readFile(this.file(id), 'utf8')));
      if (!parsed.success) throw new Error(parsed.issues[0]?.message ?? 'invalid project');
      return parsed.data;
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw err;
    }
  }

  async save(project: VideoProject) {
    await mkdir(this.dir, { recursive: true });
    const tmp = `${this.file(project.id)}.tmp`;
    await writeFile(tmp, JSON.stringify(project, null, 2), 'utf8');
    const { rename } = await import('node:fs/promises');
    await rename(tmp, this.file(project.id));
  }

  async delete(id: string) {
    await rm(this.file(id), { force: true });
  }
}

/** Asset bytes under userData/assets/<key> plus a JSON index of metadata. */
export class FileAssetStore {
  private index: Record<string, StoredAssetMetaDTO> | null = null;

  constructor(private readonly dir: string) {}

  pathFor(key: string): string {
    // Keys are generated by the app; still reject traversal defensively.
    const safe = path.basename(key);
    return path.join(this.dir, safe);
  }

  private async load(): Promise<Record<string, StoredAssetMetaDTO>> {
    if (this.index) return this.index;
    try {
      this.index = JSON.parse(await readFile(path.join(this.dir, 'index.json'), 'utf8')) as Record<
        string,
        StoredAssetMetaDTO
      >;
    } catch {
      this.index = {};
    }
    return this.index;
  }

  private async persist() {
    await mkdir(this.dir, { recursive: true });
    await writeFile(
      path.join(this.dir, 'index.json'),
      JSON.stringify(this.index ?? {}, null, 2),
      'utf8',
    );
  }

  async put(
    key: string,
    bytes: Uint8Array,
    meta: Omit<StoredAssetMetaDTO, 'key' | 'size' | 'createdAt'>,
  ): Promise<StoredAssetMetaDTO> {
    await mkdir(this.dir, { recursive: true });
    const file = this.pathFor(key);
    await writeFile(file, bytes);
    const full: StoredAssetMetaDTO = {
      ...meta,
      key: path.basename(file),
      size: bytes.byteLength,
      createdAt: new Date().toISOString(),
    };
    const idx = await this.load();
    idx[full.key] = full;
    await this.persist();
    return full;
  }

  async getMeta(key: string) {
    return (await this.load())[path.basename(key)] ?? null;
  }

  async exists(key: string) {
    return stat(this.pathFor(key))
      .then((s) => s.isFile())
      .catch(() => false);
  }

  async delete(key: string) {
    const idx = await this.load();
    delete idx[path.basename(key)];
    await rm(this.pathFor(key), { force: true });
    await this.persist();
  }

  async list() {
    return Object.values(await this.load()).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  }
}
